In [1]:
import numpy as np

array = np.array([1,6,5,3,2])
print(array)

[1 6 5 3 2]


In [2]:
type(array)

numpy.ndarray

In [3]:
for val in array:
    print(val, type(val))

1 <class 'numpy.int32'>
6 <class 'numpy.int32'>
5 <class 'numpy.int32'>
3 <class 'numpy.int32'>
2 <class 'numpy.int32'>


In [7]:
range_array = np.arange(0,23,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21])

In [13]:
int_float_list = [1,2,3,4., 5]
print("int_float_list")
for val in int_float_list:
    print(val, type(val))
mystery_array = np.array(int_float_list)
print()

print("mystery_array")
for val in mystery_array:
    print(val, type(val))
print()

print("float_array")
float_list = [1.,2.,3.,4.,5.]
float_array = np.array(float_list)
for val in float_array:
    print(val, type(val))

int_float_list
1 <class 'int'>
2 <class 'int'>
3 <class 'int'>
4.0 <class 'float'>
5 <class 'int'>

mystery_array
1.0 <class 'numpy.float64'>
2.0 <class 'numpy.float64'>
3.0 <class 'numpy.float64'>
4.0 <class 'numpy.float64'>
5.0 <class 'numpy.float64'>

float_array
1.0 <class 'numpy.float64'>
2.0 <class 'numpy.float64'>
3.0 <class 'numpy.float64'>
4.0 <class 'numpy.float64'>
5.0 <class 'numpy.float64'>


In [14]:
two_dim_list = [[1,3,5], [6,7,8], [1,5,7]]
two_dim_list

[[1, 3, 5], [6, 7, 8], [1, 5, 7]]

In [19]:
for val in two_dim_list:
    print(val)

[1, 3, 5]
[6, 7, 8]
[1, 5, 7]


In [21]:
two_dim_array = np.array(two_dim_list)
two_dim_list

[[1, 3, 5], [6, 7, 8], [1, 5, 7]]

In [22]:
for array in two_dim_array:
    print(array)
    for val in array:
        print(val)

[1 3 5]
1
3
5
[6 7 8]
6
7
8
[1 5 7]
1
5
7


In [24]:
array = np.zeros((3,3))
array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
array[0][0] = 1
array[1][1] = 3
array[2][2] = 2
array

array([[1., 0., 0.],
       [0., 3., 0.],
       [0., 0., 2.]])

In [29]:
zero_lst_of_lsts = [[0,0,0], [0,0,0], [0,0,0]]
zero_array_of_arrays = np.array(zero_lst_of_lsts)
zero_array_of_arrays

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [31]:
zero_array_of_arrays[0][0] = 4
zero_array_of_arrays

array([[4, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
np.zeros((3,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [33]:
import numpy as np

np.log(np.e)

1.0

In [34]:
np.log10(10)

1.0

In [36]:
np.log10(100)

2.0

In [39]:
for i in range(10, 1000, 10):
    print(i, np.log10(i))

10 1.0
20 1.3010299956639813
30 1.4771212547196624
40 1.6020599913279623
50 1.6989700043360187
60 1.7781512503836436
70 1.845098040014257
80 1.9030899869919435
90 1.954242509439325
100 2.0
110 2.041392685158225
120 2.0791812460476247
130 2.113943352306837
140 2.146128035678238
150 2.1760912590556813
160 2.2041199826559246
170 2.230448921378274
180 2.255272505103306
190 2.278753600952829
200 2.3010299956639813
210 2.322219294733919
220 2.342422680822206
230 2.361727836017593
240 2.380211241711606
250 2.3979400086720375
260 2.4149733479708178
270 2.4313637641589874
280 2.4471580313422194
290 2.462397997898956
300 2.4771212547196626
310 2.4913616938342726
320 2.505149978319906
330 2.5185139398778875
340 2.531478917042255
350 2.5440680443502757
360 2.5563025007672873
370 2.568201724066995
380 2.57978359661681
390 2.591064607026499
400 2.6020599913279625
410 2.6127838567197355
420 2.6232492903979003
430 2.6334684555795866
440 2.6434526764861874
450 2.6532125137753435
460 2.662757831681574
4